Project1/force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment on a post with text by a user. Has a score.</description>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Comment__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <description>The Post this comment was made on</description>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Comment__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Its rating</description>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <description>A Topical Post to a community by a user with a score and either rich text or a url</description>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Post__c/fields/Aggregate_Score__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Score__c</fullName>
    <label>Aggregate Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Post__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The rating of the post</description>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/classes/upCascadeScore.cls
global class upCascadeScore {

	//we take the scores for the comments, sum them up, add the post's score and save as an aggregate score on the post    
    Boolean moveCommentScoreToPost() {
        Boolean ret = false;

    	List<sObject> commentScoreSumByPost_l = [SELECT Post__r.ID, SUM(score__c)sum  FROM Comment__c GROUP BY Post__r.ID ];
        Map<Id, Integer> commentScoreSumByPost_m = new Map<Id, Integer>();
        for(sObject c : commentScoreSumByPost_l) { 
            commentScoreSumByPost_m.put(c.ID, Integer.valueOf(c.get('sum')) ); 
        }

        Set<ID> postIDs_s = commentScoreSumByPost_m.keySet();
        for(sObject c: commentScoreSumByPost_l) { 
            postIDs_s.add(c.ID); 
        }

        Map<Id, Post__c> posts_m = new Map<Id, Post__c>(
            [SELECT Id, Score__c, Aggregate_Score__c FROM Post__c WHERE Id IN :postIDs_s]
        );

        for(ID i : postIDs_s) {
            posts_m.get(i).Aggregate_Score__c += commentScoreSumByPost_m.get(i) + posts_m.get(i).Score__c;
        }

		List<Database.SaveResult> lsr = Database.update(posts_m.values());

        for(Database.SaveResult sr : lsr) { 
            ret &= sr.isSuccess(); 
        }
        return ret;
    }
}